development:
  adapter: postgresql
  database: tripler_development
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: tripler_production
  pool: 5
  timeout: 5000
  host: localhost
